### ISSUE TITLE
Simple High Profile 3d Printed Case

### ISSUE THREAD

**Issue by jmo808** [dsanchezseco/punk75#2]
I've designed a simple high profile 3d printed case. It comes as two parts in order to print on most printers with alignment tabs for gluing/welding. Instead of posting it on Thingiverse I'd rather include it here in order to keep things together. I can profile STL and STEP file. If you are ok with incorporating the case in your repo, I will do a PR.

![photo_2021-02-10_13-36-05](https://user-images.githubusercontent.com/6784537/107562069-f8eca900-6ba4-11eb-9f04-08b11bcb9ffc.jpg)
![photo_2021-02-10_13-36-12](https://user-images.githubusercontent.com/6784537/107562077-fab66c80-6ba4-11eb-8908-1431faedfb66.jpg)

**Comment by dsanchezseco** [comment]
Sure, go ahead, it looks awesome!! I'm regreting now not having a 3D printer :(

**Comment by jmo808** [comment]
3d printers are almost as much of a time suck as mech keyboards so maybe it's a good thing you don't have one, though I definitely like having one! I will submit PR today sometime.
